languageCode: en-us
baseURL: "https://RiteshKumarNayak125.github.io/"
title: Ritvz
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ritesh Kumar Nayak
  description: "This is the website of Ritesh, where I share insights and educational content on red teaming. Here, I post my blogs on the latest in offensive security and cybersecurity techniques"
  keywords: [Blog, Portfolio, CyberSecurity]
  author: Ritesh Kumar Nayak
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: False
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Ritvzz"
    icon: "images/browsing.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: " Security Automation Specialist \U0001F64B"
    subtitle: "Its **Ritesh Kumar Nayak, Btech** ,
    I design AI-driven security automation and orchestration workflows across cloud and network stacks using Palo Alto NGFW, Prisma SASE, Netskope SASE, Prisma Cloud, CrowdStrike, and SOAR tools like Cortex XSOAR and Demisto."
    imageUrl: "images/Last Memory Takeoff Fond D Ecran Dessin Photo Profil Croquis.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Data Professor"
    buttons:
      - name: Certifications
        url: blogs
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Howdyyy \U0001F60F"
    Content: "Its **Ritesh Kumar Nayak, Btech** ,
    I design AI-driven security automation and orchestration workflows across cloud and network stacks using Palo Alto NGFW, Prisma SASE, Netskope SASE, Prisma Cloud, CrowdStrike, and SOAR tools like Cortex XSOAR and Demisto."

  socialIcons:
    
    
    - name: twitter
      url: "https://twitter.com/Riteshnaya49092"
    - name: linkedin
      url: "https://www.linkedin.com/in/riteshnayak125/"
    - name: github
      url: "https://github.com/RiteshKumarNayak125"
    - name: Medium
      url: "https://medium.com/@ritesh4u2020"
    - name: Instagram
      url: "https://www.instagram.com/fknritvz"
    - name: Discord
      url: "https://discordapp.com/users/739041849049743390"
    - name: Hackthebox
      url: "https://app.hackthebox.com/profile/2039818"
    - name: Spotify
      url: "https://open.spotify.com/user/dc51j4h9bm951ybqemf7itbpy?si=feba750223204a54"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1

    - identifier: Certification
      name: Certification
      url: /blogs/
      weight: 2
      
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 3

   # - identifier: infographics
    #  name: Infographics
     # url: /infographics/
      #weight: 3
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
